// scripts/players.js

// #############################################################################
// ### Player Data: Includes heightInches, weightLbs, age, attitude        ###
// ### Populated with estimates. Adjust as needed for balance/realism.      ###
// #############################################################################

let ALL_PLAYERS_DATA = [
  // Batsmen
  {
    id: 1,
    name: "Babar Azam",
    role: "Batsman",
    batting: 92,
    bowling: 10,
    fielding: 78,
    potential: 96,
    status: "domestic",
    heightInches: 71,
    weightLbs: 154,
    fitness: 95,
    age: 29,
    attitude: "Professional",
  },
  {
    id: 3,
    name: "Fakhar Zaman",
    role: "Batsman",
    batting: 80,
    bowling: 10,
    fielding: 70,
    potential: 85,
    status: "domestic",
    heightInches: 70,
    weightLbs: 172,
    fitness: 88,
    age: 34,
    attitude: "Neutral",
  },
  {
    id: 4,
    name: "Imam-ul-Haq",
    role: "Batsman",
    batting: 82,
    bowling: 5,
    fielding: 72,
    potential: 86,
    status: "domestic",
    heightInches: 69,
    weightLbs: 159,
    fitness: 90,
    age: 28,
    attitude: "Neutral",
  },
  {
    id: 5,
    name: "Abdullah Shafique",
    role: "Batsman",
    batting: 78,
    bowling: 10,
    fielding: 75,
    potential: 88,
    status: "domestic",
    heightInches: 72,
    weightLbs: 163,
    fitness: 91,
    age: 24,
    attitude: "Professional",
  },
  {
    id: 6,
    name: "Saim Ayub",
    role: "Batsman",
    batting: 75,
    bowling: 15,
    fielding: 70,
    potential: 90,
    status: "domestic",
    heightInches: 69,
    weightLbs: 150,
    fitness: 93,
    age: 22,
    attitude: "Neutral",
  },
  {
    id: 7,
    name: "Saud Shakeel",
    role: "Batsman",
    batting: 77,
    bowling: 20,
    fielding: 73,
    potential: 87,
    status: "domestic",
    heightInches: 70,
    weightLbs: 154,
    fitness: 89,
    age: 28,
    attitude: "Professional",
  },
  {
    id: 30,
    name: "Shan Masood",
    role: "Batsman",
    batting: 79,
    bowling: 5,
    fielding: 74,
    potential: 82,
    status: "domestic",
    heightInches: 73,
    weightLbs: 170,
    fitness: 92,
    age: 34,
    attitude: "Professional",
  },
  {
    id: 21,
    name: "Mohammad Huraira",
    role: "Batsman",
    batting: 72,
    bowling: 10,
    fielding: 68,
    potential: 85,
    status: "domestic",
    heightInches: 70,
    weightLbs: 154,
    fitness: 85,
    age: 21,
    attitude: "Neutral",
  },
  {
    id: 22,
    name: "Omair Bin Yousuf",
    role: "Batsman",
    batting: 70,
    bowling: 5,
    fielding: 70,
    potential: 84,
    status: "domestic",
    heightInches: 70,
    weightLbs: 156,
    fitness: 86,
    age: 25,
    attitude: "Neutral",
  },
  {
    id: 36,
    name: "Sahibzada Farhan",
    role: "Batsman",
    batting: 74,
    bowling: 5,
    fielding: 69,
    potential: 80,
    status: "domestic",
    heightInches: 69,
    weightLbs: 161,
    fitness: 87,
    age: 28,
    attitude: "Neutral",
  },
  {
    id: 37,
    name: "Tayyab Tahir",
    role: "Batsman",
    batting: 73,
    bowling: 10,
    fielding: 71,
    potential: 81,
    status: "domestic",
    heightInches: 70,
    weightLbs: 159,
    fitness: 88,
    age: 30,
    attitude: "Neutral",
  },
  {
    id: 38,
    name: "Kamran Akmal",
    role: "Wk-Batsman",
    batting: 75,
    bowling: 0,
    fielding: 70,
    potential: 78,
    status: "domestic",
    heightInches: 67,
    weightLbs: 165,
    fitness: 75,
    age: 42,
    attitude: "Neutral",
  },
  {
    id: 39,
    name: "Asif Ali",
    role: "Batsman",
    batting: 72,
    bowling: 5,
    fielding: 68,
    potential: 77,
    status: "domestic",
    heightInches: 71,
    weightLbs: 176,
    fitness: 82,
    age: 32,
    attitude: "Neutral",
  },
  {
    id: 40,
    name: "Haider Ali",
    role: "Batsman",
    batting: 68,
    bowling: 10,
    fielding: 70,
    potential: 83,
    status: "domestic",
    heightInches: 70,
    weightLbs: 159,
    fitness: 86,
    age: 23,
    attitude: "Neutral",
  },
  {
    id: 41,
    name: "Umar Akmal",
    role: "Batsman",
    batting: 70,
    bowling: 5,
    fielding: 67,
    potential: 75,
    status: "domestic",
    heightInches: 68,
    weightLbs: 172,
    fitness: 70,
    age: 33,
    attitude: "Volatile",
  },
  {
    id: 42,
    name: "Ahmed Shehzad",
    role: "Batsman",
    batting: 69,
    bowling: 5,
    fielding: 70,
    potential: 74,
    status: "domestic",
    heightInches: 71,
    weightLbs: 167,
    fitness: 80,
    age: 32,
    attitude: "Volatile",
  },
  {
    id: 60,
    name: "Zain Ul Abidin",
    role: "Batsman",
    batting: 65,
    bowling: 15,
    fielding: 68,
    potential: 80,
    status: "domestic",
    heightInches: 70,
    weightLbs: 152,
    fitness: 84,
    age: 25,
    attitude: "Neutral",
  },
  {
    id: 61,
    name: "Basit Ali (Jr)",
    role: "Batsman",
    batting: 67,
    bowling: 5,
    fielding: 66,
    potential: 81,
    status: "domestic",
    heightInches: 69,
    weightLbs: 150,
    fitness: 85,
    age: 23,
    attitude: "Neutral",
  },

  // Wicketkeepers
  {
    id: 2,
    name: "Mohammad Rizwan",
    role: "Wk-Batsman",
    batting: 88,
    bowling: 5,
    fielding: 85,
    potential: 92,
    status: "domestic",
    heightInches: 69,
    weightLbs: 150,
    fitness: 98,
    age: 31,
    attitude: "Professional",
  },
  {
    id: 8,
    name: "Azam Khan",
    role: "Wk-Batsman",
    batting: 76,
    bowling: 5,
    fielding: 65,
    potential: 84,
    status: "domestic",
    heightInches: 70,
    weightLbs: 242,
    fitness: 60,
    age: 25,
    attitude: "Neutral",
  },
  {
    id: 43,
    name: "Haseebullah Khan",
    role: "Wk-Batsman",
    batting: 70,
    bowling: 0,
    fielding: 74,
    potential: 86,
    status: "domestic",
    heightInches: 69,
    weightLbs: 148,
    fitness: 90,
    age: 21,
    attitude: "Neutral",
  },
  {
    id: 44,
    name: "Rohail Nazir",
    role: "Wk-Batsman",
    batting: 66,
    bowling: 0,
    fielding: 75,
    potential: 82,
    status: "domestic",
    heightInches: 69,
    weightLbs: 145,
    fitness: 88,
    age: 22,
    attitude: "Professional",
  },
  {
    id: 45,
    name: "Mohammad Haris",
    role: "Wk-Batsman",
    batting: 73,
    bowling: 0,
    fielding: 72,
    potential: 85,
    status: "domestic",
    heightInches: 67,
    weightLbs: 143,
    fitness: 91,
    age: 23,
    attitude: "Neutral",
  },

  // All-rounders
  {
    id: 9,
    name: "Shadab Khan",
    role: "All-Rounder",
    batting: 70,
    bowling: 80,
    fielding: 82,
    potential: 88,
    status: "domestic",
    heightInches: 70,
    weightLbs: 152,
    fitness: 94,
    age: 25,
    attitude: "Professional",
  },
  {
    id: 66,
    name: "Salman Ali Agha",
    role: "All-Rounder",
    batting: 77,
    bowling: 70,
    fielding: 72,
    potential: 82,
    status: "domestic",
    heightInches: 71,
    weightLbs: 165,
    fitness: 89,
    age: 30,
    attitude: "Professional",
  },
  {
    id: 10,
    name: "Iftikhar Ahmed",
    role: "All-Rounder",
    batting: 74,
    bowling: 65,
    fielding: 70,
    potential: 80,
    status: "domestic",
    heightInches: 70,
    weightLbs: 176,
    fitness: 85,
    age: 33,
    attitude: "Neutral",
  },
  {
    id: 11,
    name: "Mohammad Nawaz",
    role: "All-Rounder",
    batting: 65,
    bowling: 78,
    fielding: 75,
    potential: 82,
    status: "domestic",
    heightInches: 70,
    weightLbs: 161,
    fitness: 88,
    age: 30,
    attitude: "Neutral",
  },
  {
    id: 12,
    name: "Aamer Jamal",
    role: "All-Rounder",
    batting: 68,
    bowling: 77,
    fielding: 72,
    potential: 85,
    status: "domestic",
    heightInches: 71,
    weightLbs: 167,
    fitness: 90,
    age: 27,
    attitude: "Neutral",
  },
  {
    id: 31,
    name: "Imad Wasim",
    role: "All-Rounder",
    batting: 72,
    bowling: 79,
    fielding: 76,
    potential: 83,
    status: "domestic",
    heightInches: 70,
    weightLbs: 163,
    fitness: 90,
    age: 35,
    attitude: "Neutral",
  },
  {
    id: 23,
    name: "Kamran Ghulam",
    role: "All-Rounder",
    batting: 65,
    bowling: 60,
    fielding: 71,
    potential: 80,
    status: "domestic",
    heightInches: 70,
    weightLbs: 159,
    fitness: 86,
    age: 28,
    attitude: "Neutral",
  },
  {
    id: 24,
    name: "Mubasir Khan",
    role: "All-Rounder",
    batting: 60,
    bowling: 70,
    fielding: 72,
    potential: 82,
    status: "domestic",
    heightInches: 69,
    weightLbs: 150,
    fitness: 87,
    age: 22,
    attitude: "Professional",
  },
  {
    id: 46,
    name: "Qasim Akram",
    role: "All-Rounder",
    batting: 62,
    bowling: 72,
    fielding: 73,
    potential: 87,
    status: "domestic",
    heightInches: 70,
    weightLbs: 154,
    fitness: 90,
    age: 21,
    attitude: "Neutral",
  },
  {
    id: 47,
    name: "Aamer Yamin",
    role: "All-Rounder",
    batting: 58,
    bowling: 75,
    fielding: 68,
    potential: 78,
    status: "domestic",
    heightInches: 72,
    weightLbs: 172,
    fitness: 84,
    age: 33,
    attitude: "Neutral",
  },
  {
    id: 48,
    name: "Hammad Azam",
    role: "All-Rounder",
    batting: 63,
    bowling: 65,
    fielding: 69,
    potential: 75,
    status: "domestic",
    heightInches: 71,
    weightLbs: 170,
    fitness: 80,
    age: 33,
    attitude: "Neutral",
  },
  {
    id: 49,
    name: "Kashif Ali (AR)",
    role: "All-Rounder",
    batting: 69,
    bowling: 62,
    fielding: 70,
    potential: 80,
    status: "domestic",
    heightInches: 70,
    weightLbs: 163,
    fitness: 85,
    age: 26,
    attitude: "Neutral",
  },
  {
    id: 62,
    name: "Mohammad Ali",
    role: "All-Rounder",
    batting: 55,
    bowling: 79,
    fielding: 67,
    potential: 83,
    status: "domestic",
    heightInches: 72,
    weightLbs: 174,
    fitness: 87,
    age: 31,
    attitude: "Neutral",
  },

  // Fast Bowlers
  {
    id: 13,
    name: "Shaheen Afridi",
    role: "Fast Bowler",
    batting: 40,
    bowling: 93,
    fielding: 75,
    potential: 97,
    status: "domestic",
    heightInches: 78,
    weightLbs: 187,
    fitness: 92,
    age: 24,
    attitude: "Professional",
    bowlingSpeed: "145-150kph",
  },
  {
    id: 14,
    name: "Naseem Shah",
    role: "Fast Bowler",
    batting: 35,
    bowling: 89,
    fielding: 72,
    potential: 95,
    status: "domestic",
    heightInches: 72,
    weightLbs: 167,
    fitness: 94,
    age: 21,
    attitude: "Neutral",
    bowlingSpeed: "148-153kph",
  },
  {
    id: 15,
    name: "Haris Rauf",
    role: "Fast Bowler",
    batting: 30,
    bowling: 87,
    fielding: 70,
    potential: 90,
    status: "domestic",
    heightInches: 72,
    weightLbs: 172,
    fitness: 93,
    age: 30,
    attitude: "Neutral",
    bowlingSpeed: "150kph+",
  },
  {
    id: 16,
    name: "Mohammad Wasim Jr",
    role: "Fast Bowler",
    batting: 50,
    bowling: 80,
    fielding: 73,
    potential: 86,
    status: "domestic",
    heightInches: 70,
    weightLbs: 159,
    fitness: 90,
    age: 22,
    attitude: "Professional",
    bowlingSpeed: "140-145kph",
  },
  {
    id: 17,
    name: "Zaman Khan",
    role: "Fast Bowler",
    batting: 25,
    bowling: 82,
    fielding: 68,
    potential: 88,
    status: "domestic",
    heightInches: 69,
    weightLbs: 152,
    fitness: 88,
    age: 22,
    attitude: "Neutral",
    bowlingSpeed: "140kph",
  }, // Slingy
  {
    id: 18,
    name: "Ihsanullah",
    role: "Fast Bowler",
    batting: 28,
    bowling: 84,
    fielding: 67,
    potential: 89,
    status: "domestic",
    heightInches: 77,
    weightLbs: 183,
    fitness: 85,
    age: 21,
    attitude: "Neutral",
    bowlingSpeed: "145-150kph",
  },
  {
    id: 32,
    name: "Hasan Ali",
    role: "Fast Bowler",
    batting: 45,
    bowling: 81,
    fielding: 71,
    potential: 84,
    status: "domestic",
    heightInches: 70,
    weightLbs: 165,
    fitness: 87,
    age: 29,
    attitude: "Neutral",
    bowlingSpeed: "135-140kph",
  },
  {
    id: 33,
    name: "Mir Hamza",
    role: "Fast Bowler",
    batting: 33,
    bowling: 79,
    fielding: 69,
    potential: 83,
    status: "domestic",
    heightInches: 72,
    weightLbs: 170,
    fitness: 86,
    age: 31,
    attitude: "Professional",
    bowlingSpeed: "130-135kph",
  }, // Swing
  {
    id: 35,
    name: "Mohammad Abbas",
    role: "Fast Bowler",
    batting: 25,
    bowling: 86,
    fielding: 70,
    potential: 88,
    status: "domestic",
    heightInches: 71,
    weightLbs: 165,
    fitness: 89,
    age: 34,
    attitude: "Professional",
    bowlingSpeed: "130-135kph",
  }, // Seam/Swing
  {
    id: 25,
    name: "Shahnawaz Dahani",
    role: "Fast Bowler",
    batting: 20,
    bowling: 77,
    fielding: 65,
    potential: 83,
    status: "domestic",
    heightInches: 71,
    weightLbs: 163,
    fitness: 87,
    age: 25,
    attitude: "Volatile",
    bowlingSpeed: "140-145kph",
  },
  {
    id: 50,
    name: "Khurram Shahzad",
    role: "Fast Bowler",
    batting: 30,
    bowling: 78,
    fielding: 68,
    potential: 84,
    status: "domestic",
    heightInches: 72,
    weightLbs: 172,
    fitness: 86,
    age: 24,
    attitude: "Neutral",
    bowlingSpeed: "135-140kph",
  },
  {
    id: 51,
    name: "Sameen Gul",
    role: "Fast Bowler",
    batting: 28,
    bowling: 76,
    fielding: 66,
    potential: 80,
    status: "domestic",
    heightInches: 73,
    weightLbs: 174,
    fitness: 85,
    age: 25,
    attitude: "Neutral",
    bowlingSpeed: "135kph",
  },
  {
    id: 52,
    name: "Mohammad Amir",
    role: "Fast Bowler",
    batting: 38,
    bowling: 85,
    fielding: 72,
    potential: 87,
    status: "domestic",
    heightInches: 72,
    weightLbs: 167,
    fitness: 90,
    age: 32,
    attitude: "Volatile",
    bowlingSpeed: "140-145kph",
  }, // Swing
  {
    id: 53,
    name: "Umaid Asif",
    role: "Fast Bowler",
    batting: 35,
    bowling: 74,
    fielding: 65,
    potential: 77,
    status: "domestic",
    heightInches: 73,
    weightLbs: 181,
    fitness: 82,
    age: 39,
    attitude: "Neutral",
    bowlingSpeed: "130kph",
  },
  {
    id: 54,
    name: "Arshad Iqbal",
    role: "Fast Bowler",
    batting: 25,
    bowling: 75,
    fielding: 67,
    potential: 82,
    status: "domestic",
    heightInches: 74,
    weightLbs: 176,
    fitness: 86,
    age: 23,
    attitude: "Neutral",
    bowlingSpeed: "140kph",
  },
  {
    id: 63,
    name: "Akif Javed",
    role: "Fast Bowler",
    batting: 22,
    bowling: 77,
    fielding: 64,
    potential: 83,
    status: "domestic",
    heightInches: 72,
    weightLbs: 165,
    fitness: 87,
    age: 23,
    attitude: "Neutral",
    bowlingSpeed: "135-140kph",
  },

  // Spinners
  {
    id: 19,
    name: "Abrar Ahmed",
    role: "Spinner",
    batting: 30,
    bowling: 83,
    fielding: 66,
    potential: 90,
    status: "domestic",
    heightInches: 70,
    weightLbs: 154,
    fitness: 89,
    age: 25,
    attitude: "Neutral",
  },
  {
    id: 20,
    name: "Usama Mir",
    role: "Spinner",
    batting: 40,
    bowling: 78,
    fielding: 68,
    potential: 84,
    status: "domestic",
    heightInches: 72,
    weightLbs: 163,
    fitness: 88,
    age: 28,
    attitude: "Neutral",
  },
  {
    id: 34,
    name: "Zahid Mahmood",
    role: "Spinner",
    batting: 25,
    bowling: 76,
    fielding: 65,
    potential: 80,
    status: "domestic",
    heightInches: 70,
    weightLbs: 156,
    fitness: 85,
    age: 36,
    attitude: "Neutral",
  },
  {
    id: 55,
    name: "Yasir Shah",
    role: "Spinner",
    batting: 35,
    bowling: 82,
    fielding: 67,
    potential: 84,
    status: "domestic",
    heightInches: 68,
    weightLbs: 154,
    fitness: 80,
    age: 38,
    attitude: "Professional",
  },
  {
    id: 56,
    name: "Mehran Mumtaz",
    role: "Spinner",
    batting: 30,
    bowling: 74,
    fielding: 69,
    potential: 85,
    status: "domestic",
    heightInches: 69,
    weightLbs: 150,
    fitness: 89,
    age: 21,
    attitude: "Neutral",
  },
  {
    id: 57,
    name: "Sufiyan Muqeem",
    role: "Spinner",
    batting: 28,
    bowling: 73,
    fielding: 66,
    potential: 86,
    status: "domestic",
    heightInches: 69,
    weightLbs: 148,
    fitness: 90,
    age: 20,
    attitude: "Neutral",
  },
  {
    id: 58,
    name: "Ali Asfand",
    role: "Spinner",
    batting: 26,
    bowling: 70,
    fielding: 68,
    potential: 83,
    status: "domestic",
    heightInches: 70,
    weightLbs: 152,
    fitness: 88,
    age: 20,
    attitude: "Neutral",
  },
  {
    id: 59,
    name: "Faisal Akram",
    role: "Spinner",
    batting: 24,
    bowling: 71,
    fielding: 65,
    potential: 84,
    status: "domestic",
    heightInches: 69,
    weightLbs: 145,
    fitness: 87,
    age: 20,
    attitude: "Neutral",
  },
  {
    id: 64,
    name: "Sajid Khan",
    role: "Spinner",
    batting: 32,
    bowling: 80,
    fielding: 68,
    potential: 85,
    status: "domestic",
    heightInches: 70,
    weightLbs: 165,
    fitness: 86,
    age: 30,
    attitude: "Neutral",
  },
  {
    id: 65,
    name: "Noman Ali",
    role: "Spinner",
    batting: 28,
    bowling: 81,
    fielding: 65,
    potential: 82,
    status: "domestic",
    heightInches: 69,
    weightLbs: 161,
    fitness: 84,
    age: 37,
    attitude: "Professional",
  },
];

// Updated Hall of Fame List (Sorted)
const HALL_OF_FAMERS = [
  "AH Kardar",
  "Abdul Qadir",
  "Fazal Mahmood",
  "Hanif Mohammad",
  "Imran Khan",
  "Inzamam ul Haq",
  "Javed Miandad",
  "Misbah ul Haq",
  "Mushtaq Mohammad",
  "Saeed Anwar",
  "Waqar Younis",
  "Wasim Akram",
  "Younis Khan",
  "Zaheer Abbas",
].sort();

// --- Initial Pundit List Helper ---
function getInitialPundits() {
  return [
    { name: "Wasim Akram", type: "Balanced", imageFile: "pundit_akram.jpg" },
    { name: "Waqar Younis", type: "Critical", imageFile: "pundit_younis.jpg" },
    { name: "Azhar Ali", type: "Critical", imageFile: "pundit_younis.jpg" },
    { name: "Rashid Latif", type: "Critical", imageFile: "pundit_younis.jpg" },
    { name: "Ramiz Raja", type: "Critical", imageFile: "pundit_younis.jpg" },
    { name: "Shahid Afridi", type: "Balanced", imageFile: "pundit_younis.jpg" },
    { name: "Basit Ali", type: "Critical", imageFile: "pundit_younis.jpg" },
    { name: "Saeed Ajmal", type: "Critical", imageFile: "pundit_younis.jpg" },
    {
      name: "Inzamam ul Haq",
      type: "Balanced",
      imageFile: "pundit_younis.jpg",
    },
    { name: "Imran Nazir", type: "Critical", imageFile: "pundit_younis.jpg" },
    { name: "Ahmed Shehzad", type: "Critical", imageFile: "pundit_younis.jpg" },
    { name: "Shoaib Malik", type: "Supportive", imageFile: "pundit_malik.jpg" },
    {
      name: "Mohammad Hafeez",
      type: "Critical",
      imageFile: "pundit_hafeez.jpg",
    },
    { name: "Misbah ul Haq", type: "Analytical", imageFile: "pundit_haq.jpg" },
    { name: "Wahab Riaz", type: "Supportive", imageFile: "pundit_riaz.jpg" },
    {
      name: "Mohammad Yousuf",
      type: "Technical",
      imageFile: "pundit_yousuf.jpg",
    },
    {
      name: "Shoaib Akhtar",
      type: "Outspoken",
      imageFile: "pundit_akhtar.jpg",
    },
  ];
}

// --- NEW: Opponent Player Data (Example Structure - Needs full population) ---
// Key: Country Name (must match gameState.opponents keys)
const OPPONENT_SQUADS = {
  Australia: [
    { name: "David Warner", role: "Batsman", skill: 90, age: 37 },
    { name: "Travis Head", role: "Batsman", skill: 88, age: 30 },
    { name: "Steve Smith", role: "Batsman", skill: 92, age: 34 },
    { name: "Marnus Labuschagne", role: "Batsman", skill: 89, age: 29 },
    { name: "Glenn Maxwell", role: "All-Rounder", skill: 85, age: 35 },
    { name: "Mitchell Marsh", role: "All-Rounder", skill: 84, age: 32 },
    { name: "Pat Cummins", role: "Fast Bowler", skill: 91, age: 30 },
    { name: "Mitchell Starc", role: "Fast Bowler", skill: 90, age: 34 },
    { name: "Josh Hazlewood", role: "Fast Bowler", skill: 89, age: 33 },
    { name: "Adam Zampa", role: "Spinner", skill: 86, age: 31 },
    // Add more players up to ~15-20 per team
  ],
  England: [
    { name: "Jos Buttler", role: "Wk-Batsman", skill: 91, age: 33 },
    { name: "Jonny Bairstow", role: "Wk-Batsman", skill: 87, age: 34 },
    { name: "Joe Root", role: "Batsman", skill: 90, age: 33 },
    { name: "Harry Brook", role: "Batsman", skill: 88, age: 25 },
    { name: "Ben Stokes", role: "All-Rounder", skill: 89, age: 32 },
    { name: "Moeen Ali", role: "All-Rounder", skill: 83, age: 36 },
    { name: "Mark Wood", role: "Fast Bowler", skill: 89, age: 34 },
    { name: "Jofra Archer", role: "Fast Bowler", skill: 90, age: 28 }, // If fit
    { name: "Adil Rashid", role: "Spinner", skill: 87, age: 36 },
    { name: "Reece Topley", role: "Fast Bowler", skill: 84, age: 30 },
    // ...
  ],
  India: [
    { name: "Rohit Sharma", role: "Batsman", skill: 92, age: 36 },
    { name: "Virat Kohli", role: "Batsman", skill: 94, age: 35 },
    { name: "Shubman Gill", role: "Batsman", skill: 89, age: 24 },
    { name: "Suryakumar Yadav", role: "Batsman", skill: 88, age: 33 }, // T20 specialist?
    { name: "KL Rahul", role: "Wk-Batsman", skill: 87, age: 31 },
    { name: "Hardik Pandya", role: "All-Rounder", skill: 86, age: 30 },
    { name: "Ravindra Jadeja", role: "All-Rounder", skill: 88, age: 35 },
    { name: "Jasprit Bumrah", role: "Fast Bowler", skill: 95, age: 30 },
    { name: "Mohammed Siraj", role: "Fast Bowler", skill: 87, age: 30 },
    { name: "Kuldeep Yadav", role: "Spinner", skill: 86, age: 29 },
    // ...
  ],
  "New Zealand": [
    { name: "Kane Williamson", role: "Batsman", skill: 91, age: 34 },
    { name: "Devon Conway", role: "Wk-Batsman", skill: 88, age: 32 },
    { name: "Finn Allen", role: "Batsman", skill: 85, age: 25 },
    { name: "Daryl Mitchell", role: "All-Rounder", skill: 87, age: 33 },
    { name: "Glenn Phillips", role: "All-Rounder", skill: 86, age: 28 },
    { name: "Mitchell Santner", role: "All-Rounder", skill: 85, age: 33 },
    { name: "Tim Southee", role: "Fast Bowler", skill: 84, age: 36 },
    { name: "Trent Boult", role: "Fast Bowler", skill: 89, age: 35 },
    { name: "Matt Henry", role: "Fast Bowler", skill: 86, age: 33 },
    { name: "Ish Sodhi", role: "Spinner", skill: 82, age: 32 },
  ],

  "South Africa": [
    { name: "Temba Bavuma", role: "Batsman", skill: 83, age: 34 },
    { name: "Quinton de Kock", role: "Wk-Batsman", skill: 90, age: 32 },
    { name: "Aiden Markram", role: "Batsman", skill: 88, age: 30 },
    { name: "Heinrich Klaasen", role: "Wk-Batsman", skill: 87, age: 33 },
    { name: "David Miller", role: "Batsman", skill: 86, age: 35 },
    { name: "Marco Jansen", role: "All-Rounder", skill: 84, age: 24 },
    { name: "Kagiso Rabada", role: "Fast Bowler", skill: 90, age: 29 },
    { name: "Anrich Nortje", role: "Fast Bowler", skill: 89, age: 31 },
    { name: "Lungi Ngidi", role: "Fast Bowler", skill: 85, age: 28 },
    { name: "Keshav Maharaj", role: "Spinner", skill: 84, age: 34 },
  ],

  "Sri Lanka": [
    { name: "Kusal Mendis", role: "Wk-Batsman", skill: 85, age: 30 },
    { name: "Pathum Nissanka", role: "Batsman", skill: 84, age: 26 },
    { name: "Charith Asalanka", role: "Batsman", skill: 83, age: 27 },
    { name: "Dasun Shanaka", role: "All-Rounder", skill: 82, age: 33 },
    { name: "Dhananjaya de Silva", role: "All-Rounder", skill: 84, age: 32 },
    { name: "Wanindu Hasaranga", role: "All-Rounder", skill: 88, age: 27 },
    { name: "Maheesh Theekshana", role: "Spinner", skill: 86, age: 24 },
    { name: "Matheesha Pathirana", role: "Fast Bowler", skill: 84, age: 22 },
    { name: "Kasun Rajitha", role: "Fast Bowler", skill: 82, age: 31 },
    { name: "Dilshan Madushanka", role: "Fast Bowler", skill: 85, age: 24 },
  ],

  Bangladesh: [
    { name: "Shakib Al Hasan", role: "All-Rounder", skill: 89, age: 37 },
    { name: "Litton Das", role: "Wk-Batsman", skill: 84, age: 30 },
    { name: "Najmul Hossain Shanto", role: "Batsman", skill: 83, age: 26 },
    { name: "Towhid Hridoy", role: "Batsman", skill: 81, age: 24 },
    { name: "Mahmudullah", role: "All-Rounder", skill: 80, age: 38 },
    { name: "Mehidy Hasan Miraz", role: "All-Rounder", skill: 85, age: 27 },
    { name: "Taskin Ahmed", role: "Fast Bowler", skill: 86, age: 30 },
    { name: "Mustafizur Rahman", role: "Fast Bowler", skill: 84, age: 29 },
    { name: "Shoriful Islam", role: "Fast Bowler", skill: 82, age: 23 },
    { name: "Taijul Islam", role: "Spinner", skill: 81, age: 32 },
  ],

  Afghanistan: [
    { name: "Rahmanullah Gurbaz", role: "Wk-Batsman", skill: 85, age: 23 },
    { name: "Ibrahim Zadran", role: "Batsman", skill: 84, age: 22 },
    { name: "Hashmatullah Shahidi", role: "Batsman", skill: 83, age: 30 },
    { name: "Najibullah Zadran", role: "Batsman", skill: 82, age: 31 },
    { name: "Mohammad Nabi", role: "All-Rounder", skill: 84, age: 40 },
    { name: "Azmatullah Omarzai", role: "All-Rounder", skill: 83, age: 24 },
    { name: "Rashid Khan", role: "Spinner", skill: 92, age: 26 },
    { name: "Mujeeb Ur Rahman", role: "Spinner", skill: 86, age: 24 },
    { name: "Fazalhaq Farooqi", role: "Fast Bowler", skill: 84, age: 24 },
    { name: "Naveen-ul-Haq", role: "Fast Bowler", skill: 82, age: 25 },
  ],

  "West Indies": [
    { name: "Shai Hope", role: "Wk-Batsman", skill: 86, age: 31 },
    { name: "Brandon King", role: "Batsman", skill: 84, age: 30 },
    { name: "Nicholas Pooran", role: "Wk-Batsman", skill: 88, age: 29 },
    { name: "Shimron Hetmyer", role: "Batsman", skill: 84, age: 28 },
    { name: "Rovman Powell", role: "All-Rounder", skill: 83, age: 31 },
    { name: "Jason Holder", role: "All-Rounder", skill: 85, age: 33 },
    { name: "Romario Shepherd", role: "All-Rounder", skill: 82, age: 30 },
    { name: "Alzarri Joseph", role: "Fast Bowler", skill: 86, age: 28 },
    { name: "Akeal Hosein", role: "Spinner", skill: 83, age: 31 },
    { name: "Oshane Thomas", role: "Fast Bowler", skill: 80, age: 28 },
  ],

  Ireland: [
    { name: "Andrew Balbirnie", role: "Batsman", skill: 82, age: 34 },
    { name: "Paul Stirling", role: "All-Rounder", skill: 83, age: 34 },
    { name: "Harry Tector", role: "Batsman", skill: 84, age: 25 },
    { name: "Lorcan Tucker", role: "Wk-Batsman", skill: 81, age: 28 },
    { name: "Curtis Campher", role: "All-Rounder", skill: 82, age: 25 },
    { name: "George Dockrell", role: "All-Rounder", skill: 80, age: 32 },
    { name: "Mark Adair", role: "Fast Bowler", skill: 83, age: 29 },
    { name: "Josh Little", role: "Fast Bowler", skill: 85, age: 25 },
    { name: "Graham Hume", role: "Fast Bowler", skill: 79, age: 33 },
    { name: "Andy McBrine", role: "Spinner", skill: 81, age: 31 },
  ],

  Zimbabwe: [
    { name: "Craig Ervine", role: "Batsman", skill: 81, age: 39 },
    { name: "Sikandar Raza", role: "All-Rounder", skill: 87, age: 38 },
    { name: "Sean Williams", role: "All-Rounder", skill: 85, age: 38 },
    { name: "Ryan Burl", role: "All-Rounder", skill: 80, age: 30 },
    { name: "Wessly Madhevere", role: "Batsman", skill: 78, age: 24 },
    { name: "Regis Chakabva", role: "Wk-Batsman", skill: 80, age: 36 },
    { name: "Richard Ngarava", role: "Fast Bowler", skill: 82, age: 27 },
    { name: "Blessing Muzarabani", role: "Fast Bowler", skill: 84, age: 28 },
    { name: "Tendai Chatara", role: "Fast Bowler", skill: 80, age: 33 },
    { name: "Wellington Masakadza", role: "Spinner", skill: 79, age: 31 },
  ],
};
